export { default as Homepage } from './homepage'
export { default as Games } from './games'
export { default as Pokemon } from './pokemon'
export { default as Regions } from './regions'
export { default as Game } from './game'
export { default as Region } from './region'
export { default as PokemonSingle } from './pokemonSingle'